// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://daxknkbmetzajmgdpniz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRheGtua2JtZXR6YWptZ2Rwbml6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwOTEzNTYsImV4cCI6MjA3MDY2NzM1Nn0.Q0LC9w7O1LOVwzyUG-MXKCLzgUAeO9fXo7n4HN5XlyE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});